#!/bin/sh

set -e

# Build image
docker build -t jonahgeorge/letterdrop .

docker tag jonahgeorge/letterdrop registry.heroku.com/letterdrop/web
docker push registry.heroku.com/letterdrop/web

# Run pending database migrations
# heroku run 'migrate -path migrations -database $DATABASE_URL up'
